/**
 * purge-phantom-women-races.ts
 *
 * Deletes women's road race rows that were auto-generated by the calendar sync
 * but don't actually exist on PCS (no women's edition of that race).
 *
 * A women's race is considered "phantom" if ALL of the following are true:
 *  1. gender = 'women', discipline = 'road', status = 'active'
 *  2. Zero startlist riders
 *  3. Zero results
 *  4. pcsUrl is either NULL or points to a men's page
 *     (i.e. doesn't contain a known women's slug pattern)
 *
 * Real women's races with a valid women's pcsUrl are never touched.
 * Real women's races without a pcsUrl but with an explicit women's name
 * (containing "Women", "Donne", "Femmes", "Ladies", etc.) are also kept.
 *
 * Run: cd ~/cycling-race-predictor && node_modules/.bin/tsx scripts/agents/purge-phantom-women-races.ts
 * Add --dry-run to preview without deleting.
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { db, races, raceEvents } from "./lib/db";
import { eq, sql, and } from "drizzle-orm";

const DRY_RUN = process.argv.includes("--dry-run");

// PCS slug patterns that confirm a real women's race
const WOMENS_URL_PATTERNS = [
  "-we/", "-donne/", "-femmes/", "-feminin", "-women/", "-ladies/",
  "-dames/", "-vrouwen/", "-femenina/", "-feminine/", "womens-", "women-",
  "ladies-", "donne-", "-we.", "-donne.", "giro-donne", "tour-femmes",
  "fleche-wallonne-fe", "liege-bastogne-liege-fe", "amstel-gold-race-ladies",
  "volta-a-catalunya-we", "e3-saxo-bank-classic-we", "scheldeprijs-we",
];

// Name patterns that indicate a real women's race (even with no URL yet)
const WOMENS_NAME_PATTERNS = [
  /\bwomen\b/i, /\bwomens\b/i, /\bdonne\b/i, /\bfemmes\b/i, /\bladies\b/i,
  /\bdames\b/i, /f[eé]minin/i, /\bfeminas?\b/i, /\bvrouwen\b/i, /\bfemenina\b/i,
  /\bemakumeen\b/i, /\bgiro.*women\b/i, /\btour.*femmes\b/i, /\bwe\b/i,
];

function hasWomensUrl(url: string | null): boolean {
  if (!url) return false;
  return WOMENS_URL_PATTERNS.some(p => url.toLowerCase().includes(p));
}

function hasWomensName(name: string): boolean {
  return WOMENS_NAME_PATTERNS.some(p => p.test(name));
}

async function main() {
  console.log(`\n🧹 Phantom Women's Race Purge ${DRY_RUN ? "(DRY RUN)" : ""}`);
  console.log("──────────────────────────────────────────────\n");

  const rows = await db.select({
    raceId: races.id,
    raceName: raceEvents.name,
    date: races.date,
    pcsUrl: races.pcsUrl,
    eventId: raceEvents.id,
    startlist: sql<number>`(SELECT COUNT(*) FROM race_startlist WHERE race_startlist.race_id = ${races.id})`,
    results: sql<number>`(SELECT COUNT(*) FROM race_results WHERE race_results.race_id = ${races.id})`,
  }).from(races)
    .innerJoin(raceEvents, eq(races.raceEventId, raceEvents.id))
    .where(and(
      eq(races.status, "active"),
      eq(races.gender, "women"),
      eq(raceEvents.discipline, "road")
    ))
    .orderBy(races.date);

  const phantoms: typeof rows = [];
  const kept: typeof rows = [];

  for (const r of rows) {
    const hasData = Number(r.startlist) > 0 || Number(r.results) > 0;
    const goodUrl = hasWomensUrl(r.pcsUrl);
    const goodName = hasWomensName(r.raceName);

    if (hasData || goodUrl || goodName) {
      kept.push(r);
    } else {
      phantoms.push(r);
    }
  }

  console.log(`Total women's road races: ${rows.length}`);
  console.log(`Keeping (real/confirmed): ${kept.length}`);
  console.log(`Phantoms to delete: ${phantoms.length}\n`);

  if (phantoms.length === 0) {
    console.log("Nothing to delete. ✅");
    return;
  }

  console.log("Deleting phantoms:");
  let deleted = 0;
  for (const r of phantoms) {
    console.log(`  ${r.date} | ${r.raceName} | ${r.raceId} | url=${r.pcsUrl ?? "NULL"}`);
    if (!DRY_RUN) {
      await db.delete(races).where(eq(races.id, r.raceId));
      deleted++;

      // If race_event now has no races left, delete it too
      const remaining = await db.select({ id: races.id }).from(races).where(eq(races.raceEventId, r.eventId));
      if (remaining.length === 0) {
        await db.delete(raceEvents).where(eq(raceEvents.id, r.eventId));
        console.log(`    ↳ Deleted orphan event ${r.eventId}`);
      }
    }
  }

  if (!DRY_RUN) {
    console.log(`\n✅ Deleted ${deleted} phantom races.`);
  } else {
    console.log(`\n(Dry run — nothing was changed. Re-run without --dry-run to delete.)`);
  }
}

main().catch(console.error);
